### ISSUE TITLE
Ship stats are missing

### ISSUE THREAD

**Issue by sr229** [nimiiiii/Nimi#14]
I got confirmation from @LeNitrous that the API is not fully parity with the full version since the stats property is missing from the responses.

I reviewed the responses and I can confirm this was the case so this is a urgent task to implement it.

**Comment by LeNitrous** [comment]
Fixed in https://github.com/nimiiiii/Nimi/commit/3cc2ababe2df9ebf75080ecb4fdc5bd0835c4ca5
