### ISSUE TITLE
Hololive and Universal Bulin ships not found

### ISSUE THREAD

**Issue by tommywalkie** [nimiiiii/Nimi#15]
Some ships like Minato Aqua or Universal Bulin appear in `/api/ships` and have their own ID but when using `/api/ship/[id]`, requests lead to _not found ressource_ errors. Needs investigation.
First thought : Might be a ship clan / class related issue.

**Comment by LeNitrous** [comment]
Should be fixed in https://github.com/nimiiiii/Nimi/commit/27e5e2d6d124615148409d9da45bea907a11c848
